version: 2

common: &common
  docker:
    - image: neomake/vims-for-tests:27@sha256:23daeb84b6881890b41398c7a6b7e5db508d2e69bc68a4dcb6617b77cca7ae71
  working_directory: ~/repo
  steps:
    - checkout
    - run: make --keep-going testcoverage TEST_VIM=$TEST_VIM
    - run:
        name: Upload coverage results
        command: |
          set -x
          coverage report -m --skip-covered
          coverage xml
          # -Z: exit with 1 in case of failures.
          codecov -Z -X search -X gcov -X pycov -f coverage.xml \
            -n "$CIRCLE_JOB" -F ${CIRCLE_JOB%%-*},${CIRCLE_JOB//[-.]/}
          set +x
jobs:
  nvim-master:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-master
  nvim-017:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.1.7
  nvim-020:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.2.0
  nvim-021:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.2.1
  nvim-022:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.2.2
  nvim-030:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.3.0
  vim-master:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim-master
  vim-8.0.1832:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim-8.0.1832
  vim-8.0.586:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim-8.0.586
  vim-74-xenial:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim73

  checkqa:
    <<: *common
    steps:
      - checkout
      - run: make --keep-going check check_docker check_lint_diff

workflows:
  version: 2
  test:
    jobs:
      - nvim-030
      - nvim-022
      - nvim-master
      - nvim-021
      - nvim-020
      - nvim-017
      - vim-8.0.1832
      - vim-8.0.586
      - vim-master
      - vim-74-xenial
      - vim-74-trusty
      - vim-73
      - checkqa
