version: 2

common: &common
  docker:
    - image: neomake/vims-for-tests:34@sha256:ec467e8eea3ed53f2977b2370425d188a9ddcf04efc95891a0b4383e5d342b62
  working_directory: ~/repo
  steps:
    - checkout
    - run: make --keep-going testcoverage TEST_VIM=$TEST_VIM _SED_HIGHLIGHT_ERRORS='| contrib/highlight-log vader'
    - run:
        name: Upload coverage results
        command: |
          set -x
          coverage report -m --skip-covered
          coverage xml

          # Only TRAVIS_JOB_ID is used by python-coveralls.
          TRAVIS_JOB_ID=$CIRCLE_WORKFLOW_ID COVERALLS_PARALLEL=true coveralls

          # -Z: exit with 1 in case of failures.
          codecov -Z -X search -X gcov -X pycov -f coverage.xml \
            -n "$CIRCLE_JOB" -F ${CIRCLE_JOB%%-*},${CIRCLE_JOB//[-.]/}
          set +x
jobs:
  nvim-031:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.3.1
  nvim-017:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.1.7
  vim-81:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim81
  vim-80:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim80
  vim-74-xenial:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim73

  checkqa:
    <<: *common
    steps:
      - checkout
      - run: make checkqa

  notify-coveralls:
    <<: *common
    steps:
      - run:
          name: notify Coveralls
          command: curl "https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN" -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"

workflows:
  version: 2
  test:
    jobs:
      - nvim-031
      - vim-73

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
